### ISSUE TITLE
VM x is not running. Skipping scaling

### ISSUE THREAD

**Issue by itsthejb** [fabriziosalmi/proxmox-vm-autoscale#13]
**Describe the bug**

Trailing this interesting project on a few Linux VMs. However, it's not working, erroring with `VM x is not running. Skipping scaling.`

**To Reproduce**
- Posting example output from `qm status x --verbose` in this issue
- In this case, the host is `localhost`, so I'm using the following host config:

```
proxmox_hosts:
  - name: localhost
    host: localhost
    ssh_user: root
    ssh_key: /root/.ssh/id_rsa
```

**Expected behavior**
The tool should be able to successfully query the status of the vm

**Additional context**
[out.log](https://github.com/user-attachments/files/17970624/out.log)
